### PR TITLE
Handle FFmpeg 3.2's missing AV_HWDEVICE_TYPE_NONE

### LINKED ISSUE #433: AV_HWDEVICE_TYPE_NONE was not declared
I see that recent FFMpegReader.h has:
~~~
#if IS_FFMPEG_3_2
		AVPixelFormat hw_de_av_pix_fmt = AV_PIX_FMT_NONE;
		AVHWDeviceType hw_de_av_device_type = AV_HWDEVICE_TYPE_NONE;
#endif
~~~
However AV_HWDEVICE_TYPE_NONE is not defined in ffmpeg until version 4 (git tag n4.0), despite the suggestion in doc/ HW-ACCEL.md that:
~~~
HW accel is supported from FFmpeg version 3.2 (3.3 for nVidia drivers)
~~~
Having searched various ffmpeg git tags, I think that claim is wrong. Maybe some distros have somehow backlported the hardware acceleraton stuff from 4.x to earlier versions (unlikely?).

As a result, libopenshot-0.2.4 cannot build with (for instance) ffmpeg-3.2.4 with error:
~~~
/var/tmp/SBo/libopenshot-0.2.4/src/../include/FFmpegReader.h:152:41: error: 'AV_HWDEVICE_TYPE_NONE' was not declared in this scope
   AVHWDeviceType hw_de_av_device_type = AV_HWDEVICE_TYPE_NONE;
~~~

### PR DESCRIPTION
**Pull request by ferdnyc**
As pointed out by @cwilling in #433, FFmpeg 3.2's `AVHWDeviceType` enum doesn't include an `AV_HWDEVICE_TYPE_NONE` value — it wasn't added until FFmpeg 3.4. As a workaround, we can just `#define` it to `AV_HWDEVICE_TYPE_VAAPI` in `FFmpegUtilities.h` if it doesn't exist.

Fixes #433

### CODE REVIEW

**Comment by ferdnyc** [comment]
Closing, as this isn't sufficient to fix the issues with FFmpeg 3.2.
